// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstore.proto

package petstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_available Status = 0
	Status_pending   Status = 1
	Status_sold      Status = 2
)

var Status_name = map[int32]string{
	0: "available",
	1: "pending",
	2: "sold",
}

var Status_value = map[string]int32{
	"available": 0,
	"pending":   1,
	"sold":      2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{1}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{2}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Pet struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrls            []string  `protobuf:"bytes,4,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	Tags                 []*Tag    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status               string    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Pet) Reset()         { *m = Pet{} }
func (m *Pet) String() string { return proto.CompactTextString(m) }
func (*Pet) ProtoMessage()    {}
func (*Pet) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{4}
}

func (m *Pet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pet.Unmarshal(m, b)
}
func (m *Pet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pet.Marshal(b, m, deterministic)
}
func (m *Pet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pet.Merge(m, src)
}
func (m *Pet) XXX_Size() int {
	return xxx_messageInfo_Pet.Size(m)
}
func (m *Pet) XXX_DiscardUnknown() {
	xxx_messageInfo_Pet.DiscardUnknown(m)
}

var xxx_messageInfo_Pet proto.InternalMessageInfo

func (m *Pet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pet) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Pet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pet) GetPhotoUrls() []string {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

func (m *Pet) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Pet) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UpdatePetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePetRequest) Reset()         { *m = UpdatePetRequest{} }
func (m *UpdatePetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePetRequest) ProtoMessage()    {}
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{5}
}

func (m *UpdatePetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePetRequest.Unmarshal(m, b)
}
func (m *UpdatePetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePetRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePetRequest.Merge(m, src)
}
func (m *UpdatePetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePetRequest.Size(m)
}
func (m *UpdatePetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePetRequest proto.InternalMessageInfo

func (m *UpdatePetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePetRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("petstore.Status", Status_name, Status_value)
	proto.RegisterType((*Empty)(nil), "petstore.Empty")
	proto.RegisterType((*Category)(nil), "petstore.Category")
	proto.RegisterType((*Tag)(nil), "petstore.Tag")
	proto.RegisterType((*ID)(nil), "petstore.ID")
	proto.RegisterType((*Pet)(nil), "petstore.Pet")
	proto.RegisterType((*UpdatePetRequest)(nil), "petstore.UpdatePetRequest")
}

func init() { proto.RegisterFile("petstore.proto", fileDescriptor_749e5a3d28fcc1b1) }

var fileDescriptor_749e5a3d28fcc1b1 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0xae, 0x93, 0x50,
	0x10, 0xc6, 0xcb, 0x9f, 0xcb, 0x85, 0xa9, 0xb7, 0x25, 0x13, 0x63, 0x08, 0xd1, 0x04, 0x59, 0xa1,
	0x26, 0x34, 0xa9, 0x3b, 0x77, 0x6a, 0x8d, 0xe9, 0xc6, 0x10, 0xda, 0xae, 0xcd, 0x69, 0x99, 0x20,
	0x09, 0xe5, 0x20, 0x67, 0xda, 0xa4, 0xef, 0xe3, 0x1b, 0xf8, 0x82, 0x46, 0xda, 0x42, 0x6f, 0xbb,
	0xe9, 0x6e, 0x86, 0xf9, 0xf8, 0xcd, 0xf7, 0x9d, 0x0c, 0x8c, 0x6a, 0x62, 0xc5, 0xb2, 0xa1, 0xb8,
	0x6e, 0x24, 0x4b, 0xb4, 0xcf, 0xbd, 0xff, 0x3a, 0x97, 0x32, 0x2f, 0x69, 0x22, 0xea, 0x62, 0x22,
	0xaa, 0x4a, 0xb2, 0xe0, 0x42, 0x56, 0xea, 0xa8, 0x0b, 0x1f, 0xe1, 0xe1, 0xdb, 0xb6, 0xe6, 0x43,
	0x18, 0x83, 0xfd, 0x55, 0x30, 0xe5, 0xb2, 0x39, 0xe0, 0x08, 0xf4, 0x22, 0xf3, 0xb4, 0x40, 0x8b,
	0x8c, 0x54, 0x2f, 0x32, 0x44, 0x30, 0x2b, 0xb1, 0x25, 0x4f, 0x0f, 0xb4, 0xc8, 0x49, 0xdb, 0x3a,
	0x7c, 0x07, 0xc6, 0x52, 0xe4, 0x77, 0x49, 0x5f, 0x82, 0x3e, 0x9f, 0x5d, 0x2b, 0xc3, 0xbf, 0x1a,
	0x18, 0x09, 0xf1, 0x0d, 0x21, 0x06, 0x7b, 0x73, 0x32, 0xd2, 0x52, 0x86, 0x53, 0x8c, 0xbb, 0x70,
	0x67, 0x8b, 0x69, 0xa7, 0xe9, 0x36, 0x1a, 0xfd, 0x46, 0x7c, 0x03, 0x50, 0xff, 0x92, 0x2c, 0x7f,
	0xee, 0x9a, 0x52, 0x79, 0x66, 0x60, 0x44, 0x4e, 0xea, 0xb4, 0x5f, 0x56, 0x4d, 0xa9, 0xf0, 0x2d,
	0x98, 0x2c, 0x72, 0xe5, 0x3d, 0x04, 0x46, 0x34, 0x9c, 0x3e, 0xf5, 0xf8, 0xa5, 0xc8, 0xd3, 0x76,
	0x84, 0xaf, 0xc0, 0x52, 0x2c, 0x78, 0xa7, 0x3c, 0xab, 0xe5, 0x9e, 0xba, 0xf0, 0x07, 0xb8, 0xab,
	0x3a, 0x13, 0x4c, 0x09, 0x71, 0x4a, 0xbf, 0x77, 0xa4, 0xf8, 0x9e, 0x37, 0xb8, 0xe0, 0x19, 0x97,
	0xbc, 0xf7, 0x31, 0x58, 0x8b, 0xb6, 0xc2, 0x27, 0x70, 0xc4, 0x5e, 0x14, 0xa5, 0x58, 0x97, 0xe4,
	0x0e, 0x70, 0x08, 0x8f, 0x35, 0x55, 0x59, 0x51, 0xe5, 0xae, 0x86, 0x36, 0x98, 0x4a, 0x96, 0x99,
	0xab, 0x4f, 0xff, 0x68, 0x30, 0x4e, 0x4e, 0x76, 0x17, 0xd4, 0xec, 0x8b, 0x0d, 0xe1, 0x07, 0x80,
	0xef, 0xc4, 0x09, 0xf1, 0x97, 0xc3, 0x7c, 0x86, 0x2f, 0xfa, 0x38, 0xf3, 0x99, 0x7f, 0x11, 0x2e,
	0x21, 0x0e, 0x07, 0xf8, 0x09, 0x9c, 0x2e, 0x00, 0xfa, 0xfd, 0xf4, 0x3a, 0x95, 0x3f, 0xee, 0x67,
	0xc7, 0x0b, 0x19, 0x60, 0x04, 0xd6, 0xe7, 0x2c, 0xfb, 0xff, 0xe3, 0x73, 0xec, 0xcd, 0x96, 0xb5,
	0xd5, 0x5e, 0xd7, 0xc7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x6b, 0x9e, 0x33, 0x97, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetstoreServiceClient is the client API for PetstoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetstoreServiceClient interface {
	GetPetByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Pet, error)
	UpdatePet(ctx context.Context, in *UpdatePetRequest, opts ...grpc.CallOption) (*Empty, error)
	AddPet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error)
}

type petstoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPetstoreServiceClient(cc *grpc.ClientConn) PetstoreServiceClient {
	return &petstoreServiceClient{cc}
}

func (c *petstoreServiceClient) GetPetByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Pet, error) {
	out := new(Pet)
	err := c.cc.Invoke(ctx, "/petstore.PetstoreService/GetPetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petstoreServiceClient) UpdatePet(ctx context.Context, in *UpdatePetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/petstore.PetstoreService/UpdatePet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petstoreServiceClient) AddPet(ctx context.Context, in *Pet, opts ...grpc.CallOption) (*Pet, error) {
	out := new(Pet)
	err := c.cc.Invoke(ctx, "/petstore.PetstoreService/AddPet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetstoreServiceServer is the server API for PetstoreService service.
type PetstoreServiceServer interface {
	GetPetByID(context.Context, *ID) (*Pet, error)
	UpdatePet(context.Context, *UpdatePetRequest) (*Empty, error)
	AddPet(context.Context, *Pet) (*Pet, error)
}

// UnimplementedPetstoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPetstoreServiceServer struct {
}

func (*UnimplementedPetstoreServiceServer) GetPetByID(ctx context.Context, req *ID) (*Pet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPetByID not implemented")
}
func (*UnimplementedPetstoreServiceServer) UpdatePet(ctx context.Context, req *UpdatePetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePet not implemented")
}
func (*UnimplementedPetstoreServiceServer) AddPet(ctx context.Context, req *Pet) (*Pet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPet not implemented")
}

func RegisterPetstoreServiceServer(s *grpc.Server, srv PetstoreServiceServer) {
	s.RegisterService(&_PetstoreService_serviceDesc, srv)
}

func _PetstoreService_GetPetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetstoreServiceServer).GetPetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/petstore.PetstoreService/GetPetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetstoreServiceServer).GetPetByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetstoreService_UpdatePet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetstoreServiceServer).UpdatePet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/petstore.PetstoreService/UpdatePet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetstoreServiceServer).UpdatePet(ctx, req.(*UpdatePetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetstoreService_AddPet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetstoreServiceServer).AddPet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/petstore.PetstoreService/AddPet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetstoreServiceServer).AddPet(ctx, req.(*Pet))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetstoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "petstore.PetstoreService",
	HandlerType: (*PetstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPetByID",
			Handler:    _PetstoreService_GetPetByID_Handler,
		},
		{
			MethodName: "UpdatePet",
			Handler:    _PetstoreService_UpdatePet_Handler,
		},
		{
			MethodName: "AddPet",
			Handler:    _PetstoreService_AddPet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "petstore.proto",
}
