// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstore.proto

package petstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_available Status = 0
	Status_pending   Status = 1
	Status_sold      Status = 2
)

var Status_name = map[int32]string{
	0: "available",
	1: "pending",
	2: "sold",
}

var Status_value = map[string]int32{
	"available": 0,
	"pending":   1,
	"sold":      2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{0}
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Tag struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetByIDRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{2}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Pet struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhotoUrls            []string  `protobuf:"bytes,4,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
	Tags                 []*Tag    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status               Status    `protobuf:"varint,6,opt,name=status,proto3,enum=petstore.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Pet) Reset()         { *m = Pet{} }
func (m *Pet) String() string { return proto.CompactTextString(m) }
func (*Pet) ProtoMessage()    {}
func (*Pet) Descriptor() ([]byte, []int) {
	return fileDescriptor_749e5a3d28fcc1b1, []int{3}
}

func (m *Pet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pet.Unmarshal(m, b)
}
func (m *Pet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pet.Marshal(b, m, deterministic)
}
func (m *Pet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pet.Merge(m, src)
}
func (m *Pet) XXX_Size() int {
	return xxx_messageInfo_Pet.Size(m)
}
func (m *Pet) XXX_DiscardUnknown() {
	xxx_messageInfo_Pet.DiscardUnknown(m)
}

var xxx_messageInfo_Pet proto.InternalMessageInfo

func (m *Pet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pet) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Pet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pet) GetPhotoUrls() []string {
	if m != nil {
		return m.PhotoUrls
	}
	return nil
}

func (m *Pet) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Pet) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_available
}

func init() {
	proto.RegisterEnum("petstore.Status", Status_name, Status_value)
	proto.RegisterType((*Category)(nil), "petstore.Category")
	proto.RegisterType((*Tag)(nil), "petstore.Tag")
	proto.RegisterType((*GetByIDRequest)(nil), "petstore.GetByIDRequest")
	proto.RegisterType((*Pet)(nil), "petstore.Pet")
}

func init() { proto.RegisterFile("petstore.proto", fileDescriptor_749e5a3d28fcc1b1) }

var fileDescriptor_749e5a3d28fcc1b1 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3d, 0x6f, 0xab, 0x40,
	0x10, 0x34, 0x1f, 0xe6, 0xc1, 0x5a, 0xe6, 0xa1, 0xad, 0x90, 0xf5, 0x9e, 0x44, 0xa8, 0x48, 0x0a,
	0x2c, 0x91, 0x22, 0x7d, 0x12, 0xc9, 0x4a, 0x2a, 0x84, 0x9d, 0x3a, 0x3a, 0x9b, 0x15, 0x39, 0x89,
	0x70, 0x84, 0x5b, 0x5b, 0xf2, 0x0f, 0xcc, 0xff, 0x8a, 0x84, 0x3f, 0xc8, 0x47, 0x93, 0xee, 0x6e,
	0x76, 0x6e, 0x66, 0x6e, 0x16, 0xfc, 0x96, 0x58, 0xb3, 0xea, 0x28, 0x6d, 0x3b, 0xc5, 0x0a, 0xdd,
	0xd3, 0x7d, 0xf6, 0xaf, 0x52, 0xaa, 0xaa, 0x69, 0x2e, 0x5a, 0x39, 0x17, 0x4d, 0xa3, 0x58, 0xb0,
	0x54, 0x8d, 0x3e, 0xf0, 0xe2, 0x14, 0xdc, 0x3b, 0xc1, 0x54, 0xa9, 0x6e, 0x8f, 0x3e, 0x98, 0xb2,
	0x0c, 0x8d, 0xc8, 0x48, 0xc6, 0x85, 0x29, 0x4b, 0x44, 0xb0, 0x1b, 0xf1, 0x4a, 0xa1, 0x19, 0x19,
	0x89, 0x57, 0xf4, 0xe7, 0xf8, 0x12, 0xac, 0x95, 0xa8, 0x7e, 0x45, 0x8d, 0xc0, 0x5f, 0x10, 0xdf,
	0xee, 0x1f, 0xee, 0x0b, 0x7a, 0xdb, 0x92, 0xe6, 0xef, 0xaf, 0xe2, 0x77, 0x03, 0xac, 0x9c, 0x7e,
	0xe0, 0x98, 0x82, 0xbb, 0x39, 0x86, 0xea, 0x15, 0x27, 0x19, 0xa6, 0xe7, 0xff, 0x9d, 0xe2, 0x16,
	0x67, 0xce, 0xd9, 0xdd, 0x1a, 0xdc, 0xf1, 0x3f, 0x40, 0xfb, 0xa2, 0x58, 0x3d, 0x6f, 0xbb, 0x5a,
	0x87, 0x76, 0x64, 0x25, 0x5e, 0xe1, 0xf5, 0xc8, 0x53, 0x57, 0x6b, 0xbc, 0x00, 0x9b, 0x45, 0xa5,
	0xc3, 0x71, 0x64, 0x25, 0x93, 0x6c, 0x3a, 0xc8, 0xaf, 0x44, 0x55, 0xf4, 0x23, 0x4c, 0xc0, 0xd1,
	0x2c, 0x78, 0xab, 0x43, 0x27, 0x32, 0x12, 0x3f, 0x0b, 0x06, 0xd2, 0xb2, 0xc7, 0x8b, 0xe3, 0xfc,
	0x2a, 0x05, 0xe7, 0x80, 0xe0, 0x14, 0x3c, 0xb1, 0x13, 0xb2, 0x16, 0xeb, 0x9a, 0x82, 0x11, 0x4e,
	0xe0, 0x4f, 0x4b, 0x4d, 0x29, 0x9b, 0x2a, 0x30, 0xd0, 0x05, 0x5b, 0xab, 0xba, 0x0c, 0xcc, 0xec,
	0x11, 0xfe, 0xe6, 0x47, 0xa9, 0x25, 0x75, 0x3b, 0xb9, 0x21, 0xbc, 0x01, 0x58, 0x10, 0xe7, 0x87,
	0xbe, 0x30, 0x1c, 0xac, 0xbe, 0x56, 0x38, 0xfb, 0x94, 0x34, 0x27, 0x8e, 0x47, 0x6b, 0xa7, 0xdf,
	0xe3, 0xf5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x8c, 0x5f, 0x35, 0x01, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetstoreServiceClient is the client API for PetstoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetstoreServiceClient interface {
	GetPetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Pet, error)
}

type petstoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPetstoreServiceClient(cc *grpc.ClientConn) PetstoreServiceClient {
	return &petstoreServiceClient{cc}
}

func (c *petstoreServiceClient) GetPetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*Pet, error) {
	out := new(Pet)
	err := c.cc.Invoke(ctx, "/petstore.PetstoreService/GetPetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetstoreServiceServer is the server API for PetstoreService service.
type PetstoreServiceServer interface {
	GetPetByID(context.Context, *GetByIDRequest) (*Pet, error)
}

// UnimplementedPetstoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPetstoreServiceServer struct {
}

func (*UnimplementedPetstoreServiceServer) GetPetByID(ctx context.Context, req *GetByIDRequest) (*Pet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPetByID not implemented")
}

func RegisterPetstoreServiceServer(s *grpc.Server, srv PetstoreServiceServer) {
	s.RegisterService(&_PetstoreService_serviceDesc, srv)
}

func _PetstoreService_GetPetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetstoreServiceServer).GetPetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/petstore.PetstoreService/GetPetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetstoreServiceServer).GetPetByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PetstoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "petstore.PetstoreService",
	HandlerType: (*PetstoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPetByID",
			Handler:    _PetstoreService_GetPetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "petstore.proto",
}
